#include "weather-symbol.h"
#include "gfx.h"

WeatherSymbol::WeatherSymbol(Gfx *gfx_p) {
  gfx = gfx_p;
}

void WeatherSymbol::update(weather_symbol_t symbol) {

}

void WeatherSymbol::update(weather_code_t code) {
  update(getSymbol(code));
}

void WeatherSymbol::updateInterior(void) {
  update(WEATHER_SYMBOL_INT);
}

weather_symbol_t WeatherSymbol::getSymbol(weather_code_t code) {
  switch (code) {
    case WEATHER_CODE_CLEAR:
      //todo: moon by time of day
      return WEATHER_SYMBOL_SUN;
    case WEATHER_CODE_PARTLY_CLOUDY:
      //todo: moon by time of day
      return WEATHER_SYMBOL_CLOUDY_SUN;
    case WEATHER_CODE_CLOUDY:
    case WEATHER_CODE_OVERCAST:
      return WEATHER_SYMBOL_CLOUDY;
    case WEATHER_CODE_FOG:
    case WEATHER_CODE_MIST:
    case WEATHER_CODE_FREEZING_FOG:
      return WEATHER_SYMBOL_FOG;
    case WEATHER_CODE_HEAVY_RAIN:
    case WEATHER_CODE_LIGHT_RAIN:
    case WEATHER_CODE_PATCHY_RAIN_POSSIBLE:
    case WEATHER_CODE_PATCHY_LIGHT_RAIN:
    case WEATHER_CODE_PATCHY_LIGHT_DRIZZLE:
    case WEATHER_CODE_LIGHT_RAIN_SHOWER:
    case WEATHER_CODE_MODERATE_OR_HEAVY_RAIN_SHOWER:
    case WEATHER_CODE_TORRENTIAL_RAIN_SHOWER:
    case WEATHER_CODE_HEAVY_RAIN_AT_TIMES:
    case WEATHER_CODE_MODERATE_RAIN_AT_TIMES:
      return WEATHER_SYMBOL_RAIN;
    case WEATHER_CODE_HEAVY_SNOW:
    case WEATHER_CODE_MODERATE_SNOW:
    case WEATHER_CODE_MODERATE_OR_HEAVY_SNOW_SHOWERS:
    case WEATHER_CODE_LIGHT_SNOW:
    case WEATHER_CODE_LIGHT_SNOW_SHOWERS:
    case WEATHER_CODE_PATCHY_SNOW_POSSIBLE:
    case WEATHER_CODE_PATCHY_HEAVY_SNOW:
    case WEATHER_CODE_PATCHY_MODERATE_SNOW:
    case WEATHER_CODE_PATCHY_LIGHT_SNOW:
    case WEATHER_CODE_BLOWING_SNOW:
    case WEATHER_CODE_BLIZZARD:
      return WEATHER_SYMBOL_SNOW;
    case WEATHER_CODE_LIGHT_SLEET:
    case WEATHER_CODE_LIGHT_SLEET_SHOWERS:
    case WEATHER_CODE_MODERATE_OR_HEAVY_SLEET:
    case WEATHER_CODE_MODERATE_OR_HEAVY_SLEET_SHOWERS:
    case WEATHER_CODE_PATCHY_SLEET_POSSIBLE:
    case WEATHER_CODE_FREEZING_DRIZZLE:
    case WEATHER_CODE_PATCHY_FREEZING_DRIZZLE_POSSIBLE:
    case WEATHER_CODE_HEAVY_FREEZING_DRIZZLE:
    case WEATHER_CODE_LIGHT_FREEZING_RAIN:
    case WEATHER_CODE_MODERATE_OR_HEAVY_FREEZING_RAIN:
    case WEATHER_CODE_ICE_PELLETS:
    case WEATHER_CODE_LIGHT_SHOWERS_OF_ICE_PELLETS:
    case WEATHER_CODE_MODERATE_OR_HEAVY_SHOWERS_OF_ICE_PELLETS:
      return WEATHER_SYMBOL_SLEET;
    case WEATHER_CODE_THUNDERY_OUTBREAKS_POSSIBLE:
    case WEATHER_CODE_PATCHY_LIGHT_RAIN_WITH_THUNDER:
    case WEATHER_CODE_MODERATE_OR_HEAVY_RAIN_WITH_THUNDER:
    case WEATHER_CODE_PATCHY_LIGHT_SNOW_WITH_THUNDER:
    case WEATHER_CODE_MODERATE_OR_HEAVY_SNOW_WITH_THUNDER:
      return WEATHER_SYMBOL_LIGHTNING;
  }
  return WEATHER_SYMBOL_UNKNOWN;
}
